apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapprc
  namespace: test-ns
spec:
  replicas: 5
  selector:
    app: javawebapp
  template:   #Pod Template
    metadata:
      name: javawebapp
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: samuelpolagani98/java-web-application:1
        ports:
        - containerPort: 8080

