apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
  namespace: test-ns
spec:
  containers:
    - name: javawebappcontainer
      image: samuelpolagani98/java-web-application:1
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80 
    targetPort: 8080
