apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: javanetworkpolicy
  namespace: test-ns
spec:
  podSelector:
    matchLabels:
      app: javawebapp
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default
    ports:
    - protocol: TCP
      port: 8080
