apiVersion: v1
kind: ConfigMap
metadata:
  name: javawebappconfig
  namespace: test-ns
data:
  tomcat-users.xml: |
    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">
      <user username="admin" password="admin" roles="manager-gui,admin-gui"/>
    </tomcat-users>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdep
  namespace: test-ns
spec:
  revisionHistoryLimit: 5
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      #maxUnavailable: 50%
      #maxSurge: 50%
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: samuelpolagani98/java-web-application:5
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: javawebappvol
          mountPath: /usr/local/tomcat/conf/tomcat-users.xml
          subPath: tomcat-users.xml
      volumes:
      - name: javawebappvol
        configMap:
          name: javawebappconfig
          items:
          - key: tomcat-users.xml
            path: tomcat-users.xml
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappdepsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
