apiVersion: v1
kind: LimitRange
metadata:
  name: testns-limitrange
  namespace: test-ns
spec:
  limits:
  - default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
