apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mavenwebapprs
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - image: samuelpolagani98/maven-webapplication:1
        name: mavenwebappcontainer
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappservice
  namespace: test-ns
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
