apiVersion: v1
kind: Pod
metadata:
  name: mavenwebappstatic
  namespace: test-ns
  labels:
    app: mavenwebapp
spec:
  containers:
  - name: mavenwebapp
    image: samuelpolagani98/maven-webapplication:1
    ports:
    - containerPort: 80
