apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginsdaemonset
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginxcontainer
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  namespace: test-ns
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
