apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginxnetworkpolicy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          teamDl: loginteam
    ports:
    - protocol: TCP
      port: 80
