#ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: springappconfig
  namespace: test-ns
data:
  mongodbusername: devdb
---
#Secret
apiVersion: v1
kind: Secret
metadata:
  name: springappsecret
  namespace: test-ns
type: Opaque
stringData:
  mongodbpassword: devdb@123
