apiVersion: apps/v1
kind: Deployment
metadata:
  name: springmongodeployment
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: springmongoapp
  replicas: 1
  template:
    metadata:
      name: springmongopod
      labels:
        app: springmongoapp
    spec:
      containers:
      - name: springmongocontainer
        image: samuelpolagani98/sprintbootmongo:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
          - name: MONGO_DB_USERNAME
            value: devdb
          - name: MONGO_DB_PASSWORD
            value: devdb123
          - name: MONGO_DB_HOSTNAME
            value: mongoservice
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springbootmongohpa
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springmongodeployment
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
---
#Service for springboot application
apiVersion: v1
kind: Service
metadata:
  name: springappmongoservice
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: springmongoapp
  ports:
  - port: 80
    targetPort: 8080
---
#ReplicaSet for mongoDB
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongocontainer
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb123
        volumeMounts:
        - name: mongodbdataval
          mountPath: /data/db
      volumes:
      - name: mongodbdataval
        persistentVolumeClaim:
                claimName: mongodbpvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbpvc
  namespace: test-ns
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
#Service for mongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongoservice
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

